version: "3.10"

services:
  app:
    build: app
    ports:
      - 8000:8000
    networks:
      AIservice:
        aliases:
          - app.docker

  frontend:
    build: frontend
    ports:
      - 3000:3000
    networks:
      AIservice:
        aliases:
          - frontend.docker
    depends_on:
      - app

networks:
  AIservice:
    external: true
