FROM python:3.10-slim

WORKDIR / 
COPY . .
RUN pip install --no-cache-dir -r requirements.txt 
RUN apt-get update && apt-get install -y vim 

EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000" , "--reload"]
